version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-sonabel
    environment:
      POSTGRES_DB: sonabel_bd
      POSTGRES_USER: sonabel
      POSTGRES_PASSWORD: sonabel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  postgres_data:
    driver: local
  grafana-storage:
