version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-sonabel
    environment:
      POSTGRES_DB: sonabel_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11tati173
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local