global:
  scrape_interval: 15s  # fréquence de collecte des métriques

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8888'
          - 'host.docker.internal:8082'
          - 'host.docker.internal:8083'
          - 'host.docker.internal:8084'
          - 'host.docker.internal:8084'
