spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8085
            predicates:
              - Path=/api/aboones/**
          - id: r2
            uri: http://localhost:8082
            predicates:
              - Path=/api/facturation/**
          - id: r3
            uri: http://localhost:8084
            predicates:
              - Path=/api/intervention/**
          - id: r4
            uri: http://localhost:8083
            predicates:
              - Path=/api/consommation/**
    discovery:
      locator:
        enabled: true # Permet de détecter automatiquement les services depuis Eureka

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
