server:
  port: 8888

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive

  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/auth/**
        - id: consommation
          uri: http://localhost:8083
          predicates:
            - Path=/api/consommation/**
        - id: facturation
          uri: http://localhost:8082
          predicates:
            - Path=/api/facturation/**
        - id: aboone
          uri: http://localhost:8085
          predicates:
            - Path=/api/aboones/**
        - id: intervention
          uri: http://localhost:8084
          predicates:
            - Path=/api/intervention/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
